/* Autogenerated with Kurento Idl */

/*
 * (C) Copyright 2013-2015 Kurento (http://kurento.org/)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

var inherits = require('inherits');

var kurentoClient = require('kurento-client');

var disguise = kurentoClient.disguise;

var checkType      = kurentoClient.checkType;
var ChecktypeError = checkType.ChecktypeError;


var Transaction = kurentoClient.TransactionsManager.Transaction;

var Filter = kurentoClient.register.abstracts.Filter;


function noop(error, result) {
  if (error) console.trace(error);

  return result
};


/**
 * Create a :rom:cls:`BackgroundExtractor`
 *
 * @classdesc
 *  Filter that converts the user background to alpha
 *
 * @extends module:core/abstracts.Filter
 *
 * @constructor module:backgroundextractor.BackgroundExtractorFilter
 */
function BackgroundExtractorFilter(){
  BackgroundExtractorFilter.super_.call(this);
};
inherits(BackgroundExtractorFilter, Filter);


//
// Public methods
//

/**
 * Allow to activate/deactivate the proccessing
 *
 * @alias module:backgroundextractor.BackgroundExtractorFilter.activateProcessing
 *
 * @param {external:Boolean} process
 *  TRUE activates the processing and FALSE deactivates the processing
 *
 * @param {module:backgroundextractor.BackgroundExtractorFilter~activateProcessingCallback} [callback]
 *
 * @return {external:Promise}
 */
BackgroundExtractorFilter.prototype.activateProcessing = function(process, callback){
  var transaction = (arguments[0] instanceof Transaction)
                  ? Array.prototype.shift.apply(arguments)
                  : undefined;

  //  
  // checkType('boolean', 'process', process, {required: true});
  //  

  var params = {
    process: process
  };

  callback = (callback || noop).bind(this)

  return disguise(this._invoke(transaction, 'activateProcessing', params, callback), this)
};
/**
 * @callback module:backgroundextractor.BackgroundExtractorFilter~activateProcessingCallback
 * @param {external:Error} error
 */


/**
 * @alias module:backgroundextractor.BackgroundExtractorFilter.constructorParams
 *
 * @property {module:core.MediaPipeline} mediaPipeline
 *  the {@link module:core.MediaPipeline MediaPipeline} to which the filter 
 *  belongs
 */
BackgroundExtractorFilter.constructorParams = {
  mediaPipeline: {
    type: 'kurento.MediaPipeline',
    required: true
  }
};

/**
 * @alias module:backgroundextractor.BackgroundExtractorFilter.events
 *
 * @extends module:core/abstracts.Filter.events
 */
BackgroundExtractorFilter.events = Filter.events;


/**
 * Checker for {@link module:backgroundextractor.BackgroundExtractorFilter}
 *
 * @memberof module:backgroundextractor
 *
 * @param {external:String} key
 * @param {module:backgroundextractor.BackgroundExtractorFilter} value
 */
function checkBackgroundExtractorFilter(key, value)
{
  if(!(value instanceof BackgroundExtractorFilter))
    throw ChecktypeError(key, BackgroundExtractorFilter, value);
};


module.exports = BackgroundExtractorFilter;

BackgroundExtractorFilter.check = checkBackgroundExtractorFilter;
